# Generated by Django 6.0.2 on 2026-03-29 02:49

from django.db import migrations, models


def forwards_map_legacy_roles(apps, schema_editor):
    Profile = apps.get_model("sportscio", "Profile")
    for p in Profile.objects.all():
        if p.role == "student":
            p.role = "member"
        elif p.role == "exec":
            p.role = "officer"
        else:
            continue
        p.save(update_fields=["role"])


def backwards_map_legacy_roles(apps, schema_editor):
    Profile = apps.get_model("sportscio", "Profile")
    for p in Profile.objects.all():
        if p.role == "member":
            p.role = "student"
        elif p.role == "officer":
            p.role = "exec"
        elif p.role == "user_admin":
            p.role = "exec"
        else:
            continue
        p.save(update_fields=["role"])


class Migration(migrations.Migration):

    dependencies = [
        ("sportscio", "0003_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="user_type",
            new_name="role",
        ),
        migrations.RunPython(forwards_map_legacy_roles, backwards_map_legacy_roles),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Member"),
                    ("officer", "Officer"),
                    ("user_admin", "User administrator"),
                ],
                default="member",
                max_length=20,
            ),
        ),
    ]
