# Generated by Django 6.0.2 on 2026-03-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportscio", "0004_profile_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
