# Generated by Django 6.0.2 on 2026-03-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportscio", "0006_s3_uploads"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_president",
            field=models.BooleanField(default=False),
        ),
    ]
