# Generated by Django 6.0.2 on 2026-03-29 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sportscio", "0007_president_flag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_president",
        ),
    ]
