# Generated by Django 6.0.2 on 2026-04-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportscio", "0008_remove_president"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Member"),
                    ("officer", "Club leader"),
                    ("user_admin", "User administrator"),
                ],
                default="member",
                max_length=20,
            ),
        ),
    ]
