# Generated by Django 6.0.2 on 2026-04-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportscio', '0009_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
