# Generated by Django 6.0.2 on 2026-04-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportscio', '0010_profile_email_notifications_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sms_notifications',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
