# Generated by Cursor on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportscio", "0011_remove_profile_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]

