# Generated by Cursor on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportscio", "0012_event_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]

