# AI Use: Generated with Gemini 3 Flash on 2026-04-17.
# Prompt: "Configure Django settings for a production-ready app with AWS S3 storage, Gmail SMTP email, Django Channels for WebSockets, and role-based access control middleware".
# Notes: This settings file is tailored for deployment on Heroku, with environment variable configurations for sensitive information and production optimizations like WhiteNoise for static file handling. It also includes setup for Django Q and Channels, as well as context processors and middleware for user role management.

"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

import dj_database_url
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-%mqi8^0+l$q+$jrtamim2ew5ibwgr=z!&yhr5nwour4lr=_cq0"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['swe-group8-6275098586a9.herokuapp.com', '0.0.0.0', '127.0.0.1', 'localhost', '.herokuapp.com']

# Heroku terminates TLS; the dyno sees HTTP.
if os.environ.get("DYNO"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition
SOCIALACCOUNT_LOGIN_ON_GET = True
SITE_ID = 2

INSTALLED_APPS = [
    "daphne",
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_q",
    "storages",
    "sportscio.apps.SportscioConfig",
    "django.contrib.sites",
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'background_task',
]

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        # Force Google to show the account chooser each time.
        # Prevents "logged out, but it logs back into the other Google account" confusion.
        "AUTH_PARAMS": {"access_type": "online", "prompt": "select_account"},
    }
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "sportscio.middleware.UserAdministratorAppRestrictionMiddleware",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "sportscio.context_processors.roles",
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

WSGI_APPLICATION = "mysite.wsgi.application"
ASGI_APPLICATION = "mysite.asgi.application"

# Django Channels
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}

# Database
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',
        conn_max_age=600,
    )
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "en-us"
# App is currently only used in US/Eastern.
# Django still stores datetimes in UTC when USE_TZ=True, but template display/localtime uses this TZ.
TIME_ZONE = "America/New_York"
USE_I18N = True
USE_TZ = True

# Static files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = "static/"

# S3 Configuration
USE_S3 = os.environ.get("USE_S3", "").lower() in ("1", "true", "yes")
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

if USE_S3:
    AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
    AWS_SECRET_ACCESS_KEY = os.environ["AWS_SECRET_ACCESS_KEY"]
    AWS_STORAGE_BUCKET_NAME = os.environ["AWS_STORAGE_BUCKET_NAME"]
    AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME", "us-east-1")
    AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_LOCATION = "media"
    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }
    domain = f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"
    MEDIA_URL = f"https://{domain}/{AWS_LOCATION}/"
else:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/sportscio/dashboard/"
LOGOUT_REDIRECT_URL = "/login/"

# --- Email Configuration ---
# Local Dev (DEBUG=True): Prints to console
# Production (DEBUG=False): Sends via Gmail SMTP
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    DEFAULT_FROM_EMAIL = "notifications@localhost"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.environ.get("GMAIL_USER") # e.g., yourname@gmail.com
    EMAIL_HOST_PASSWORD = os.environ.get("GMAIL_APP_PASSWORD") # Your 16-character App Password
    DEFAULT_FROM_EMAIL = os.environ.get("GMAIL_USER")

Q_CLUSTER = {
    'name': 'SportsCIOQueue',
    'orm': 'default',  # Use Django's default database
    'workers': 1,      # Heroku free/mini dynos handle 1 worker best
    'timeout': 60,
    'retry': 120,
}